version: '3.1'

services:
  mysql:
    image: mysql
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: medibot
      MYSQL_DATABASE: medibotdb
      MYSQL_USER: medibot
      MYSQL_PASSWORD: medibot
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
