version: '3.1'

services:
  mysql:
    image: mysql
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ecohouses
      MYSQL_DATABASE: ecohouses
      MYSQL_USER: ecohouses
      MYSQL_PASSWORD: ecohouses
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
